### ISSUE TITLE
No results /item and /itemasuser commands

### ISSUE THREAD

**Issue by Fracticus** [TheSilentPro/SlimeBot#2]
![Screenshot_20220326-020927](https://user-images.githubusercontent.com/102395700/160218724-d679e52e-8199-4ac1-8838-f00dfde877ed.png)

I'm not in game. The bot shows a link between Minecraft and Discord, as other commands show results. The /item and /itemasuser commands don't get the results. I'm not a server owner.

**Comment by TheSilentPro** [comment]
What is the FULL command you're running?
There is no /itemasuser command?

**Comment by Fracticus** [comment]
> command

The owner tested every command again, with no error messages to console, so the origin was on my side. The /itemasuser is from something else, but due to set-up, the difference was indistinguishable.
